#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.name
  labels:
    service: #@ data.values.name
spec:
  replicas: 1
  selector:
    matchLabels:
      service: #@ data.values.name
  template:
    metadata:
      labels:
        service: #@ data.values.name
    spec:
      restartPolicy: Always
      containers:
        - image: #@ data.values.images.app
          name: app
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          env:
            - name: "REDIS_ADDR"
              value: #@ data.values.name + "-redis:6379"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: #@ data.values.name
  name: #@ data.values.name
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: #@ data.values.name
