---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-app

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-app-psp
roleRef:
  kind: ClusterRole
  name: psp:vmware-system-restricted
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: example-app
